name: Docker Compose CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose

      - name: Build and run the Docker Compose services
        run: |
          docker-compose -f docker-compose.yml up --build -d

      - name: Run tests (optional)
        run: |
          docker-compose exec app pytest  # Commande pour tester l'application, à adapter

      - name: Shut down the Docker Compose services
        run: |
          docker-compose down
